name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version (Release Version | Match AppVersion)
        required: true
        type: string

permissions: write-all

jobs:
  build:
    name: Generate APK and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build the APK
        run: ./gradlew assembleRelease

      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ github.event.inputs.version }}",
              sha: context.sha
            })

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ github.event.inputs.version }}"
          tag_name: "v${{ github.event.inputs.version }}"
          files: app/build/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release.apk


